import { readFileSync, writeFileSync } from 'fs';

const existingData = JSON.parse(readFileSync('data.json', 'utf8'));

const newRecipes = [
    // RAMADHAN SPECIALS
    { id: "menusa_0111", title: "Kolak Pisang Ubi", origin_region: "Nusantara", cuisine_subtype: "Nusantara", servings: 6, prep_time: 15, cook_time: 30, total_time: 45, difficulty: "mudah", ingredients: [{ name: "pisang kepok, ubi kuning, gula aren, santan, pandan", quantity: 800, unit: "g" }], steps: [{ number: 1, text: "Rebus ubi dan pandan dengan gula aren sampai empuk, masukkan pisang matang dan santan kental, aduk mendidih." }], tags: ["takjil", "manis hangat", "ramadhan"], categories: ["Minuman"] },
    { id: "menusa_0112", title: "Es Buah Segar", origin_region: "Nusantara", cuisine_subtype: "Nusantara", servings: 10, prep_time: 30, cook_time: 0, total_time: 30, difficulty: "mudah", ingredients: [{ name: "aneka buah (semangka, melon, apel, anggur), sirup cocopandan, susu kental manis", quantity: 1500, unit: "g" }], steps: [{ number: 1, text: "Potong dadu semua buah, campur dengan bongkahan es, tuang sirup merah dan susu kental pekat." }], tags: ["takjil", "es manis", "ramadhan"], categories: ["Minuman"] },
    { id: "menusa_0113", title: "Sop Buah Kuah Susu", origin_region: "Bandung, Jawa Barat", cuisine_subtype: "Nusantara", servings: 8, prep_time: 25, cook_time: 0, total_time: 25, difficulty: "mudah", ingredients: [{ name: "naga merah, alpukat, stroberi, jelly, susu evaporasi", quantity: 1000, unit: "g" }], steps: [{ number: 1, text: "Sajikan potongan buah dan jelly kenyal dengan kuah susu evaporasi kental yang manis gurih dingin." }], tags: ["takjil", "es buah", "ramadhan"], categories: ["Minuman"] },
    { id: "menusa_0114", title: "Biji Salak Ubi Ungu", origin_region: "Nusantara", cuisine_subtype: "Nusantara", servings: 5, prep_time: 30, cook_time: 25, total_time: 55, difficulty: "sedang", ingredients: [{ name: "ubi ungu, tepung sagu, gula merah, santan kental", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Buat bulatan kenyal dari ubi ungu, rebus merapung lalu padukan dengan kinca gula merah dan saus santan gurih." }], tags: ["takjil", "kue basah", "ramadhan"], categories: ["Cemilan"] },
    { id: "menusa_0115", title: "Ayam Kecap Sahur Praktis", origin_region: "Nusantara", cuisine_subtype: "Nusantara", servings: 4, prep_time: 10, cook_time: 20, total_time: 30, difficulty: "mudah", ingredients: [{ name: "ayam potong kecil, kecap manis, bawang bombay", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Tumis bawang bombay, masukkan ayam cepat matang, bumbui kecap tebal berkaramel, masak sebentar di waktu sahur." }], tags: ["sahur", "praktis", "ayam", "ramadhan"], categories: ["Utama"] },
    { id: "menusa_0116", title: "Tumis Telur Tomat Sahur", origin_region: "Nusantara", cuisine_subtype: "Nusantara", servings: 2, prep_time: 5, cook_time: 10, total_time: 15, difficulty: "mudah", ingredients: [{ name: "telur ayam kocok, buah tomat, saus tiram, daun bawang", quantity: 250, unit: "g" }], steps: [{ number: 1, text: "Orak arik telur lembut (jangan terlalu kering), angkat. Tumis potongan tomat sampai layu berair, masukkan kembali telur lalu aduk rata saus tiram." }], tags: ["sahur", "praktis", "telur", "ramadhan"], categories: ["Lauk"] },
    { id: "menusa_0117", title: "Opor Ayam Lebaran", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 8, prep_time: 30, cook_time: 60, total_time: 90, difficulty: "sedang", ingredients: [{ name: "ayam kampung, santan cair, santan kental, bumbu kuning", quantity: 1200, unit: "g" }], steps: [{ number: 1, text: "Masak ayam kampung perlahan di bumbu kuning kuah santan cair memanjang sampai empuk, kentalkan dengan santan tebal di akhir." }], tags: ["buka puasa", "hari raya", "ramadhan"], categories: ["Utama"] },
    { id: "menusa_0118", title: "Sambal Goreng Ati Kentang", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 6, prep_time: 30, cook_time: 40, total_time: 70, difficulty: "sedang", ingredients: [{ name: "ati ampela ayam, kentang dadu, cabai merah petai", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Goreng dadu kentang dan rebus ati ampela. Tumis bumbu pedas manis pekat bersantan, masukkan hati dan kentang bersama petai." }], tags: ["lauk berat", "pedas", "ramadhan"], categories: ["Lauk"] },
    { id: "menusa_0119", title: "Es Campur Sirup Merah", origin_region: "Nusantara", cuisine_subtype: "Nusantara", servings: 5, prep_time: 30, cook_time: 0, total_time: 30, difficulty: "mudah", ingredients: [{ name: "cincau hitam, tape singkong, kolang-kaling, es serut, sirup", quantity: 800, unit: "g" }], steps: [{ number: 1, text: "Tata semua isian campur kaya tekstur, taburi es serut gunung lantas guyur dengan sirup frambozen dan kental manis." }], tags: ["takjil", "es campur", "ramadhan"], categories: ["Minuman"] },
    { id: "menusa_0120", title: "Sayur Sop Sosis Sahur", origin_region: "Nusantara", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 20, total_time: 35, difficulty: "mudah", ingredients: [{ name: "wortel, buncis, kentang, sosis sapi, kaldu ayam", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Rebus sayuran padat dan sosis secara bertahap dalam bening kaldu sedap bernuansa pala dan merica untuk menyegarkan perut sahur." }], tags: ["sahur", "kuah segar", "ramadhan"], categories: ["Sup"] }
];

const allData = [...existingData, ...newRecipes];
writeFileSync('data.json', JSON.stringify(allData, null, 2));
console.log('Added 10 special Ramadhan recipes to data.json, total is now 120');
