import { readFileSync, writeFileSync } from 'fs';

const existingData = JSON.parse(readFileSync('data.json', 'utf8'));

const newRecipes = [
    // CEMILAN (Snacks)
    { id: "menusa_0091", title: "Kue Pukis", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 10, prep_time: 60, cook_time: 20, total_time: 80, difficulty: "sedang", ingredients: [{ name: "tepung terigu, santan, ragi", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Diamkan adonan pukis sampai mengembang, lalu tuang pada cetakan panas." }], tags: ["kue manis", "jajanan pasar"], categories: ["cemilan"] },
    { id: "menusa_0092", title: "Lemper Ayam", origin_region: "Jawa", cuisine_subtype: "Nusantara", servings: 8, prep_time: 40, cook_time: 40, total_time: 80, difficulty: "sedang", ingredients: [{ name: "ketan, ayam suwir berbumbu", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Kukus ketan dengan santan, isikan ayam suwir, lalu bungkus daun pisang." }], tags: ["ketan", "kue asin"], categories: ["cemilan"] },
    { id: "menusa_0093", title: "Kue Lumpur Surga", origin_region: "Kalimantan Selatan", cuisine_subtype: "Nusantara", servings: 5, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "mudah", ingredients: [{ name: "santan, pandan, telur", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Kukus adonan hijau pandan lalu timpa dengan adonan putih santan gurih manis." }], tags: ["kue basah", "santan gurih"], categories: ["cemilan"] },
    { id: "menusa_0094", title: "Biji Salak (Kolak)", origin_region: "Sumatera Barat", cuisine_subtype: "Nusantara", servings: 5, prep_time: 30, cook_time: 30, total_time: 60, difficulty: "sedang", ingredients: [{ name: "ubi jalar kuning, tepung sagu", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Bentuk bulat adonan ubi sagu, rebus, lalu siram dengan kuah gula merah santan." }], tags: ["manis", "ubi jalar"], categories: ["cemilan"] },
    { id: "menusa_0095", title: "Pempek Dos", origin_region: "Sumatera Selatan", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 30, total_time: 60, difficulty: "sedang", ingredients: [{ name: "tepung sagu, terigu, tanpa ikan", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Rebus adonan pempek tanpa ikan ini, lalu goreng dan sajikan dengan cuko merah." }], tags: ["gurih kenyal", "tanpa ikan"], categories: ["cemilan"] },
    { id: "menusa_0096", title: "Cireng Bumbu Rujak", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 20, total_time: 40, difficulty: "mudah", ingredients: [{ name: "tepung tapioka, bawang putih", quantity: 300, unit: "g" }], steps: [{ number: 1, text: "Goreng pipih adonan tapioka biang lalu cocol dengan bumbu rujak pedas manis asam." }], tags: ["kenyal", "gorengan"], categories: ["cemilan"] },
    { id: "menusa_0097", title: "Pastel Sayur Telur", origin_region: "Nusantara", cuisine_subtype: "Nusantara", servings: 10, prep_time: 45, cook_time: 30, total_time: 75, difficulty: "sedang", ingredients: [{ name: "tepung terigu, wortel, bihun, telur", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Gilas kulit pastel, isikan sayur basah dan telur, jepit ulir pinggirnya dan goreng." }], tags: ["goreng ranyah", "jajanan gurih"], categories: ["cemilan"] },
    { id: "menusa_0098", title: "Klepon Ketan", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 6, prep_time: 30, cook_time: 20, total_time: 50, difficulty: "mudah", ingredients: [{ name: "tepung ketan, pandan, gula merah", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Isi bulatan ketan hijau pandan dengan irisan gula merah, rebus sampai mengapung, balur parutan kelapa." }], tags: ["manis legit", "kue basah"], categories: ["cemilan"] },
    { id: "menusa_0099", title: "Risol Mayo", origin_region: "DKI Jakarta", cuisine_subtype: "Nusantara", servings: 8, prep_time: 30, cook_time: 20, total_time: 50, difficulty: "sedang", ingredients: [{ name: "kulit lumpia/risol, mayo, smoke beef, telur", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Gulung isian mayo daging telur di kulit risol, balur tepung roti lalu goreng." }], tags: ["gorengan", "gurih creamy"], categories: ["cemilan"] },
    { id: "menusa_0100", title: "Kue Talam Pandan", origin_region: "Betawi", cuisine_subtype: "Nusantara", servings: 8, prep_time: 20, cook_time: 40, total_time: 60, difficulty: "sedang", ingredients: [{ name: "tepung beras, santan, pandan", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Kukus adonan pandan beras lalu tuang adonan santan gurih di atasnya." }], tags: ["kue talam", "pandan"], categories: ["cemilan"] },

    // MINUMAN (Drinks)
    { id: "menusa_0101", title: "Es Dawet Ayu", origin_region: "Banjarnegara, Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 15, total_time: 45, difficulty: "sedang", ingredients: [{ name: "tepung beras, pandan, santan, gula merah", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Cetak adonan beras hijau pandan di air es, siram kuah santan dan sirup gula merah wangi nangka." }], tags: ["es", "manis segar"], categories: ["minuman"] },
    { id: "menusa_0102", title: "Wedang Ronde", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 20, total_time: 50, difficulty: "sedang", ingredients: [{ name: "tepung ketan, kacang tanah, jahe", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Sajikan bulatan ketan isi kacang kupas dalam kuah jahe gula merah hangat." }], tags: ["wedang hangat", "jahe"], categories: ["minuman"] },
    { id: "menusa_0103", title: "Es Kuwut", origin_region: "Bali", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 0, total_time: 15, difficulty: "mudah", ingredients: [{ name: "kelapa muda, melon, jeruk nipis, selasih", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Campur serutan melon dan kelapa dengan perasan jeruk nipis dan sirup melon segar." }], tags: ["es segar", "jeruk nipis"], categories: ["minuman"] },
    { id: "menusa_0104", title: "Es Pisang Ijo", origin_region: "Makassar, Sulawesi Selatan", cuisine_subtype: "Nusantara", servings: 5, prep_time: 45, cook_time: 30, total_time: 75, difficulty: "sulit", ingredients: [{ name: "pisang raja, tepung beras, pandan, sirup DHT", quantity: 800, unit: "g" }], steps: [{ number: 1, text: "Balut pisang kukus dengan dadar hijau pandan, sajikan dengan bubur sumsum dan sirup pisang ambon merah." }], tags: ["es pisang", "manis dingin"], categories: ["minuman"] },
    { id: "menusa_0105", title: "Bandrek", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 10, cook_time: 20, total_time: 30, difficulty: "mudah", ingredients: [{ name: "jahe bakar, gula merah, kayu manis, cengkeh", quantity: 300, unit: "g" }], steps: [{ number: 1, text: "Rebus jahe memar dan berbagai rempah kayu manis dengan gula merah, bisa disajikan dengan kerukan kelapa." }], tags: ["wedang", "rempah kencang"], categories: ["minuman"] },
    { id: "menusa_0106", title: "Es Selendang Mayang", origin_region: "DKI Jakarta", cuisine_subtype: "Nusantara", servings: 5, prep_time: 30, cook_time: 15, total_time: 45, difficulty: "sedang", ingredients: [{ name: "tepung hunkwe, santan, sirup merah", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Potong kotak adonan hunkwe lapis tiga warna, siram kuah santan dan sirup merah es." }], tags: ["es", "hunkwe manis"], categories: ["minuman"] },
    { id: "menusa_0107", title: "Wedang Uwuh", origin_region: "DI Yogyakarta", cuisine_subtype: "Nusantara", servings: 4, prep_time: 5, cook_time: 15, total_time: 20, difficulty: "mudah", ingredients: [{ name: "daun cengkeh, kayu secang, jahe, daun pala", quantity: 150, unit: "g" }], steps: [{ number: 1, text: "Rebus atau seduh dedaunan rempah kering dan kayu secang sampai air kemerahan hangat." }], tags: ["rempah", "minuman kesehatan"], categories: ["minuman"] },
    { id: "menusa_0108", title: "Es Cendol", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 20, total_time: 50, difficulty: "sedang", ingredients: [{ name: "tepung hunkwe/beras, pandan suji", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Cetak cendol dari adonan beras hunkwe hijau pekat, sajikan bersama santan encer dan tebalnya kinca gula aren." }], tags: ["es cendol", "gula aren"], categories: ["minuman"] },
    { id: "menusa_0109", title: "Bajigur", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 10, cook_time: 20, total_time: 30, difficulty: "mudah", ingredients: [{ name: "santan, kopi hitam bubuk, gula aren, jahe", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Masak perlahan santan bersama gula aren, sedikit jahe, dan sejumput bubuk kopi lalu saring." }], tags: ["santan hangat", "kopi"], categories: ["minuman"] },
    { id: "menusa_0110", title: "Teh Talua (Teh Telur)", origin_region: "Sumatera Barat", cuisine_subtype: "Nusantara", servings: 2, prep_time: 10, cook_time: 5, total_time: 15, difficulty: "mudah", ingredients: [{ name: "teh hitam pekat, kuning telur ayam kampung, jeruk nipis", quantity: 200, unit: "g" }], steps: [{ number: 1, text: "Kocok kuning telur dan gula sampai mengembang/kental, seduh dengan teh panas pekat dan kucuran nipis." }], tags: ["teh", "penambah stamina"], categories: ["minuman"] }
];

const allData = [...existingData, ...newRecipes];
writeFileSync('data.json', JSON.stringify(allData, null, 2));
console.log('Added 20 new recipes (10 snacks, 10 drinks) to data.json, total is now 110');
