import { readFileSync, writeFileSync } from 'fs';

const existingData = JSON.parse(readFileSync('data.json', 'utf8'));

const newRecipes = [
    { id: "menusa_0021", title: "Nasi Liwet Solo", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 45, total_time: 65, difficulty: "sedang", ingredients: [{ name: "beras", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Masak beras dengan santan." }], tags: ["santan", "nasi"], categories: ["masakan utama"] },
    { id: "menusa_0022", title: "Sate Lilit Ayam", origin_region: "Bali", cuisine_subtype: "Nusantara", servings: 5, prep_time: 30, cook_time: 20, total_time: 50, difficulty: "sedang", ingredients: [{ name: "daging ayam giling", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Lilitkan ayam pada batang serai." }], tags: ["sate", "ayam"], categories: ["lauk"] },
    { id: "menusa_0023", title: "Ayam Penyet", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 30, total_time: 45, difficulty: "mudah", ingredients: [{ name: "ayam", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Goreng ayam lalu penyet dengan sambal." }], tags: ["pedas", "ayam"], categories: ["lauk"] },
    { id: "menusa_0024", title: "Ikan Bakar Jimbaran", origin_region: "Bali", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "sedang", ingredients: [{ name: "ikan laut", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Bakar ikan dengan bumbu khas Jimbaran." }], tags: ["bakar", "ikan"], categories: ["lauk"] },
    { id: "menusa_0025", title: "Soto Kudus", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 60, total_time: 80, difficulty: "sedang", ingredients: [{ name: "ayam kampung", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Rebus kaldu ayam dan sajikan dengan kuah bening." }], tags: ["soto", "kuah"], categories: ["makanan berkuah"] },
    { id: "menusa_0026", title: "Rujak Cingur", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 0, total_time: 30, difficulty: "mudah", ingredients: [{ name: "cingur sapi", quantity: 200, unit: "g" }], steps: [{ number: 1, text: "Campur cingur dengan sayuran dan bumbu petis." }], tags: ["rujak", "khas"], categories: ["jajanan"] },
    { id: "menusa_0027", title: "Mie Celor", origin_region: "Sumatera Selatan", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "sedang", ingredients: [{ name: "mie kuning", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Siram mie dengan kuah santan kaldu ebi." }], tags: ["mie", "kuah"], categories: ["makanan utama"] },
    { id: "menusa_0028", title: "Ayam Geprek", origin_region: "DI Yogyakarta", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 20, total_time: 40, difficulty: "mudah", ingredients: [{ name: "ayam goreng tepung", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Geprek ayam dengan sambal bawang." }], tags: ["pedas", "ayam"], categories: ["lauk"] },
    { id: "menusa_0029", title: "Sate Padang", origin_region: "Sumatera Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 45, total_time: 75, difficulty: "sulit", ingredients: [{ name: "daging sapi", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Rebus daging dan siram dengan kuah kental kuning." }], tags: ["sate", "daging"], categories: ["lauk"] },
    { id: "menusa_0030", title: "Pecel Lele", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 20, total_time: 35, difficulty: "mudah", ingredients: [{ name: "ikan lele", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Goreng lele dan sajikan dengan sambal tomat." }], tags: ["goreng", "ikan"], categories: ["lauk"] },
    { id: "menusa_0031", title: "Nasi Uduk", origin_region: "DKI Jakarta", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 40, total_time: 55, difficulty: "mudah", ingredients: [{ name: "beras", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Masak beras dengan santan dan serai." }], tags: ["nasi", "santan"], categories: ["masakan utama"] },
    { id: "menusa_0032", title: "Seblak", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 2, prep_time: 15, cook_time: 15, total_time: 30, difficulty: "mudah", ingredients: [{ name: "kerupuk mentah", quantity: 150, unit: "g" }], steps: [{ number: 1, text: "Rebus kerupuk dengan bumbu kencur pedas." }], tags: ["pedas", "kuah"], categories: ["jajanan"] },
    { id: "menusa_0033", title: "Babi Guling", origin_region: "Bali", cuisine_subtype: "Nusantara", servings: 10, prep_time: 60, cook_time: 240, total_time: 300, difficulty: "sulit", ingredients: [{ name: "babi utuh", quantity: 5000, unit: "g" }], steps: [{ number: 1, text: "Guling babi utuh dengan bumbu rempah Bali." }], tags: ["babi", "panggang"], categories: ["masakan utama"] },
    { id: "menusa_0034", title: "Selat Solo", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 60, total_time: 90, difficulty: "sedang", ingredients: [{ name: "daging sapi", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Rebus daging dengan kecap dan bumbu rempah." }], tags: ["daging", "kuah manis"], categories: ["makanan berkuah"] },
    { id: "menusa_0035", title: "Pindang Patin", origin_region: "Sumatera Selatan", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "sedang", ingredients: [{ name: "ikan patin", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Masak kuah pindang asam segar lalu masukkan patin." }], tags: ["ikan", "asam segar"], categories: ["makanan berkuah"] },
    { id: "menusa_0036", title: "Ayam Goreng Kalasan", origin_region: "DI Yogyakarta", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 40, total_time: 60, difficulty: "sedang", ingredients: [{ name: "ayam", quantity: 800, unit: "g" }], steps: [{ number: 1, text: "Ungkep ayam dengan air kelapa lalu goreng." }], tags: ["goreng", "manis gurih"], categories: ["lauk"] },
    { id: "menusa_0037", title: "Ketoprak", origin_region: "DKI Jakarta", cuisine_subtype: "Nusantara", servings: 2, prep_time: 20, cook_time: 0, total_time: 20, difficulty: "mudah", ingredients: [{ name: "tahu, bihun, tauge", quantity: 300, unit: "g" }], steps: [{ number: 1, text: "Campur bahan dengan bumbu kacang bawang putih." }], tags: ["kacang", "sayur"], categories: ["jajanan"] },
    { id: "menusa_0038", title: "Tongseng Kambing", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 45, total_time: 65, difficulty: "sedang", ingredients: [{ name: "daging kambing", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Tumis dengan bumbu gulai dan kecap." }], tags: ["kambing", "kuah kental"], categories: ["makanan berkuah"] },
    { id: "menusa_0039", title: "Sate Taichan", origin_region: "DKI Jakarta", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 15, total_time: 35, difficulty: "mudah", ingredients: [{ name: "dada ayam", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Bakar ayam polos dan sajikan dengan sambal rawit." }], tags: ["sate", "pedas"], categories: ["lauk"] },
    { id: "menusa_0040", title: "Soto Mie Bogor", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 90, total_time: 120, difficulty: "sedang", ingredients: [{ name: "daging sapi & mie kuning", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Rebus kuah kaldu sapi bening dan tuang ke mie." }], tags: ["soto", "kuah bening"], categories: ["makanan berkuah"] },
    { id: "menusa_0041", title: "Empal Gentong", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 90, total_time: 120, difficulty: "sedang", ingredients: [{ name: "daging sapi", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Masak kuah santan kuning dengan daging sapi." }], tags: ["santan", "berkuah"], categories: ["makanan berkuah"] },
    { id: "menusa_0042", title: "Nasi Kuning", origin_region: "Nasional", cuisine_subtype: "Nusantara", servings: 6, prep_time: 20, cook_time: 45, total_time: 65, difficulty: "mudah", ingredients: [{ name: "beras", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Masak beras dengan santan dan kunyit." }], tags: ["nasi", "gurih"], categories: ["masakan utama"] },
    { id: "menusa_0043", title: "Iga Penyet", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 90, total_time: 120, difficulty: "sedang", ingredients: [{ name: "iga sapi", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Presto iga lalu goreng, penyet di atas sambal." }], tags: ["daging", "pedas"], categories: ["lauk"] },
    { id: "menusa_0044", title: "Sayur Lodeh", origin_region: "Jawa", cuisine_subtype: "Nusantara", servings: 5, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "mudah", ingredients: [{ name: "sayuran campur", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Masak sayuran dalam kuah santan gurih." }], tags: ["sayur", "santan"], categories: ["sayur"] },
    { id: "menusa_0045", title: "Opor Ayam", origin_region: "Jawa", cuisine_subtype: "Nusantara", servings: 6, prep_time: 20, cook_time: 45, total_time: 65, difficulty: "sedang", ingredients: [{ name: "ayam", quantity: 800, unit: "g" }], steps: [{ number: 1, text: "Masak ayam dalam kuah santan kuning pucat." }], tags: ["ayam", "santan"], categories: ["lauk"] },
    { id: "menusa_0046", title: "Sate Buntel", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 30, total_time: 60, difficulty: "sedang", ingredients: [{ name: "daging kambing cincang", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Buntel daging di tusuk sate dan bakar." }], tags: ["sate", "kambing"], categories: ["lauk"] },
    { id: "menusa_0047", title: "Tengkleng", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 90, total_time: 120, difficulty: "sulit", ingredients: [{ name: "tulang kambing", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Masak tulang kambing dengan kuah gulai encer." }], tags: ["kambing", "kuah pedas"], categories: ["makanan berkuah"] },
    { id: "menusa_0048", title: "Asinan Betawi", origin_region: "DKI Jakarta", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 0, total_time: 30, difficulty: "mudah", ingredients: [{ name: "sayuran segar", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Campur dengan kuah bumbu kacang asam pedas." }], tags: ["sayur", "segar"], categories: ["salad tradisional"] },
    { id: "menusa_0049", title: "Kerak Telor", origin_region: "DKI Jakarta", cuisine_subtype: "Nusantara", servings: 2, prep_time: 15, cook_time: 20, total_time: 35, difficulty: "sedang", ingredients: [{ name: "beras ketan & telur bebek", quantity: 200, unit: "g" }], steps: [{ number: 1, text: "Panggang di wajan tanpa minyak dengan serundeng." }], tags: ["telur", "panggang"], categories: ["jajanan"] },
    { id: "menusa_0050", title: "Gohu Ikan", origin_region: "Maluku", cuisine_subtype: "Nusantara", servings: 3, prep_time: 15, cook_time: 0, total_time: 15, difficulty: "mudah", ingredients: [{ name: "ikan tuna segar", quantity: 300, unit: "g" }], steps: [{ number: 1, text: "Aduk ikan mentah dengan jeruk cui, daun kemangi, dan kenari." }], tags: ["ikan mentah", "segar"], categories: ["lauk"] }
];

const allData = [...existingData, ...newRecipes];
writeFileSync('data.json', JSON.stringify(allData, null, 2));
console.log('Added 30 new recipes to data.json');
