import { readFileSync, writeFileSync } from 'fs';

const existingData = JSON.parse(readFileSync('data.json', 'utf8'));

const newRecipes = [
    { id: "menusa_0051", title: "Gepuk Daging Sapi", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 90, total_time: 110, difficulty: "sedang", ingredients: [{ name: "daging sapi", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Rebus daging, pukul-pukul, dan ungkep dengan bumbu manis guriih lalu goreng." }], tags: ["daging", "manis gurih"], categories: ["lauk"] },
    { id: "menusa_0052", title: "Soto Banjar", origin_region: "Kalimantan Selatan", cuisine_subtype: "Nusantara", servings: 5, prep_time: 30, cook_time: 60, total_time: 90, difficulty: "sedang", ingredients: [{ name: "ayam kampung", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Rebus kaldu dengan rempah kayu manis dan cengkeh." }], tags: ["soto", "rempah"], categories: ["makanan berkuah"] },
    { id: "menusa_0053", title: "Ayam Tangkap", origin_region: "Aceh", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 30, total_time: 45, difficulty: "mudah", ingredients: [{ name: "ayam", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Goreng ayam bersama daun kari, pandan, dan salam kojak." }], tags: ["goreng", "rempah daun"], categories: ["lauk"] },
    { id: "menusa_0054", title: "Cakalang Fufu", origin_region: "Sulawesi Utara", cuisine_subtype: "Nusantara", servings: 4, prep_time: 10, cook_time: 20, total_time: 30, difficulty: "mudah", ingredients: [{ name: "ikan cakalang asap", quantity: 300, unit: "g" }], steps: [{ number: 1, text: "Suwir ikan dan tumis dengan sambal rica-rica." }], tags: ["ikan asap", "pedas"], categories: ["lauk"] },
    { id: "menusa_0055", title: "Ayam Woku", origin_region: "Sulawesi Utara", cuisine_subtype: "Nusantara", servings: 5, prep_time: 20, cook_time: 40, total_time: 60, difficulty: "sedang", ingredients: [{ name: "ayam", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Masak ayam dengan bumbu kuning pedas dan kemangi berlimpah." }], tags: ["pedas", "kemangi"], categories: ["lauk"] },
    { id: "menusa_0056", title: "Soto Lamongan", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 5, prep_time: 30, cook_time: 60, total_time: 90, difficulty: "sedang", ingredients: [{ name: "ayam", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Sajikan soto dengan taburan koya kerupuk udang." }], tags: ["soto", "bubuk koya"], categories: ["makanan berkuah"] },
    { id: "menusa_0057", title: "Gadon Daging", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "mudah", ingredients: [{ name: "daging sapi cincang", quantity: 300, unit: "g" }], steps: [{ number: 1, text: "Bungkus daging cincang dan santan dalam daun pisang lalu kukus." }], tags: ["kukus", "santan"], categories: ["lauk"] },
    { id: "menusa_0058", title: "Sambal Goreng Krecek", origin_region: "DI Yogyakarta", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 30, total_time: 45, difficulty: "sedang", ingredients: [{ name: "kerupuk rambak/krecek", quantity: 150, unit: "g" }], steps: [{ number: 1, text: "Masak krecek dalam kuah santan kemerahan pedas bersama kacang tolo." }], tags: ["santan", "pedas"], categories: ["sayur"] },
    { id: "menusa_0059", title: "Sate Ambal", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "sedang", ingredients: [{ name: "ayam", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Sate ayam yang disajikan dengan saus tempe halus sebagai pengganti kacang." }], tags: ["sate", "saus tempe"], categories: ["lauk"] },
    { id: "menusa_0060", title: "Nasi Campur Bali", origin_region: "Bali", cuisine_subtype: "Nusantara", servings: 4, prep_time: 60, cook_time: 60, total_time: 120, difficulty: "sulit", ingredients: [{ name: "beras dan aneka lauk bali", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Tata nasi putih dengan sate lilit, lawar, ayam betutu, dan sambal matah." }], tags: ["nasi", "lengkap"], categories: ["masakan utama"] },
    { id: "menusa_0061", title: "Lontong Sayur Medan", origin_region: "Sumatera Utara", cuisine_subtype: "Nusantara", servings: 6, prep_time: 40, cook_time: 60, total_time: 100, difficulty: "sedang", ingredients: [{ name: "lontong, nangka muda, pakis", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Sajikan lontong dengan sayur gurih pedas, tauco, dan teri kacang." }], tags: ["santan", "lontong"], categories: ["masakan utama"] },
    { id: "menusa_0062", title: "Gulai Daun Singkong", origin_region: "Sumatera Barat", cuisine_subtype: "Nusantara", servings: 5, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "mudah", ingredients: [{ name: "daun singkong muda", quantity: 300, unit: "g" }], steps: [{ number: 1, text: "Rebus daun singkong lalu masak dalam kuah gulai encer." }], tags: ["sayur", "gulai"], categories: ["sayur"] },
    { id: "menusa_0063", title: "Nasi Grombyang", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 90, total_time: 120, difficulty: "sedang", ingredients: [{ name: "daging kerbau/sapi", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Sajikan nasi dengan kuah daging berempah kluwek pucat dan irisan daging besar." }], tags: ["nasi", "kuah daging"], categories: ["masakan utama"] },
    { id: "menusa_0064", title: "Sate Maranggi", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 40, cook_time: 20, total_time: 60, difficulty: "sedang", ingredients: [{ name: "daging sapi", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Marinasi daging dengan ketumbar dan kecap lalu bakar. Sajikan tanpa saus kacang." }], tags: ["sate", "manis"], categories: ["lauk"] },
    { id: "menusa_0065", title: "Lontong Balap", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 40, total_time: 70, difficulty: "sedang", ingredients: [{ name: "tauge, tahu, lontong, lentho", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Siram bahan dengan kuah bening kaldu dan taburan lentho serta sambal petis." }], tags: ["lontong", "segar"], categories: ["masakan utama"] },
    { id: "menusa_0066", title: "Ayam Iloni", origin_region: "Gorontalo", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 45, total_time: 65, difficulty: "sedang", ingredients: [{ name: "ayam", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Ungkep ayam dengan bumbu santan pedas lalu bakar." }], tags: ["ayam", "santan bakar"], categories: ["lauk"] },
    { id: "menusa_0067", title: "Kupat Tahu", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 3, prep_time: 15, cook_time: 15, total_time: 30, difficulty: "mudah", ingredients: [{ name: "ketupat, tahu goreng, tauge", quantity: 300, unit: "g" }], steps: [{ number: 1, text: "Siram bahan dengan kuah kacang encer atau kuah kecap bawang merah." }], tags: ["ketupat", "tahu"], categories: ["masakan utama"] },
    { id: "menusa_0068", title: "Sup Konro", origin_region: "Sulawesi Selatan", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 120, total_time: 140, difficulty: "sulit", ingredients: [{ name: "iga sapi utuh", quantity: 800, unit: "g" }], steps: [{ number: 1, text: "Masak iga lama dengan bumbu rempah hitam berbahan kluwek." }], tags: ["berkuah", "iga"], categories: ["makanan berkuah"] },
    { id: "menusa_0069", title: "Nasi Jagung", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 40, total_time: 60, difficulty: "mudah", ingredients: [{ name: "beras dan beras jagung", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Kukus beras campuran jagung, sajikan dengan urapan dan ikan asin." }], tags: ["nasi", "jagung kering"], categories: ["masakan utama"] },
    { id: "menusa_0070", title: "Plecing Kangkung", origin_region: "Nusa Tenggara Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 10, total_time: 25, difficulty: "mudah", ingredients: [{ name: "kangkung segar", quantity: 200, unit: "g" }], steps: [{ number: 1, text: "Rebus kangkung, sajikan dengan sambal tomat terasi yang segar pedas." }], tags: ["sayur", "pedas segar"], categories: ["salad tradisional"] }
];

const allData = [...existingData, ...newRecipes];
writeFileSync('data.json', JSON.stringify(allData, null, 2));
console.log('Added 20 new recipes to data.json, total is now 70');
