import { readFileSync, writeFileSync } from 'fs';

const existingData = JSON.parse(readFileSync('data.json', 'utf8'));

const newRecipes = [
    { id: "menusa_0071", title: "Nasi Krawu", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 40, total_time: 60, difficulty: "sedang", ingredients: [{ name: "daging sapi", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Sajikan nasi dengan suwiran daging empuk, serundeng, dan sambal terasi." }], tags: ["nasi", "daging kelapa"], categories: ["masakan utama"] },
    { id: "menusa_0072", title: "Rujak Soto", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 60, total_time: 90, difficulty: "sulit", ingredients: [{ name: "potongan babat dan tulang sapi", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Tuang kuah soto panas ke atas sayur rujak cingur petis." }], tags: ["rujak", "soto"], categories: ["makanan utama"] },
    { id: "menusa_0073", title: "Ayam Panggang Klaten", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 60, total_time: 80, difficulty: "sedang", ingredients: [{ name: "ayam", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Ungkep ayam dengan santan dan rempah lalu panggang." }], tags: ["ayam", "panggang santan"], categories: ["lauk"] },
    { id: "menusa_0074", title: "Lapis Daging Sapi", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 60, total_time: 80, difficulty: "sedang", ingredients: [{ name: "daging sapi", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Masak daging lapis dengan bumbu kecap manis legit." }], tags: ["daging", "lapis kecap"], categories: ["lauk"] },
    { id: "menusa_0075", title: "Garang Asem Ayam", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 5, prep_time: 20, cook_time: 45, total_time: 65, difficulty: "sedang", ingredients: [{ name: "ayam", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Kukus ayam bersama belimbing wuluh dan santan berbungkus daun pisang." }], tags: ["ayam", "asam segar"], categories: ["lauk"] },
    { id: "menusa_0076", title: "Ikan Pe Asap Kuah Santan", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 30, total_time: 45, difficulty: "mudah", ingredients: [{ name: "ikan pari/pe asap", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Masak ikan asap dalam kuah santan pedas gurih." }], tags: ["ikan asap", "santan"], categories: ["makanan berkuah"] },
    { id: "menusa_0077", title: "Tahu Tek", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 3, prep_time: 20, cook_time: 15, total_time: 35, difficulty: "mudah", ingredients: [{ name: "tahu, telur, lontong", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Goreng tahu dan telur berbumbu lalu siram saus kacang petis." }], tags: ["tahu goreng", "petis"], categories: ["masakan utama"] },
    { id: "menusa_0078", title: "Ayam Bumbu Rujak", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 40, total_time: 60, difficulty: "sedang", ingredients: [{ name: "ayam", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Panggang ayam berbalut bumbu kemerahan manis pedas." }], tags: ["ayam", "bumbu rujak"], categories: ["lauk"] },
    { id: "menusa_0079", title: "Kare Rajungan", origin_region: "Jawa Timur", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "sedang", ingredients: [{ name: "kepiting rajungan", quantity: 600, unit: "g" }], steps: [{ number: 1, text: "Masak rajungan dengan bumbu kare pedas bersantan." }], tags: ["kepiting", "kare"], categories: ["makanan berkuah"] },
    { id: "menusa_0080", title: "Nasi Bejeg", origin_region: "Bali", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 40, total_time: 60, difficulty: "sedang", ingredients: [{ name: "ayam suwir, nasi pucat", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Remas/bejeg ayam suwir berbumbu bersama nasi dan rempah." }], tags: ["nasi", "ayam suwir"], categories: ["masakan utama"] },
    { id: "menusa_0081", title: "Mie Kocok", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 90, total_time: 110, difficulty: "sedang", ingredients: [{ name: "mie kuning lurus, kikil", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Kocok mie lalu siram kuah tulang sapi kental dan potongan kikil." }], tags: ["mie", "kikil sapi"], categories: ["makanan berkuah"] },
    { id: "menusa_0082", title: "Sate Buntel Sapi", origin_region: "Jawa Tengah", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 30, total_time: 50, difficulty: "sedang", ingredients: [{ name: "daging sapi cincang berlapis lemak", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Buntel/lilit sapi cincang dan bakar, siram dengan saus kecap." }], tags: ["sate", "sapi cincang"], categories: ["lauk"] },
    { id: "menusa_0083", title: "Soto Kesawan", origin_region: "Sumatera Utara", cuisine_subtype: "Nusantara", servings: 4, prep_time: 20, cook_time: 60, total_time: 80, difficulty: "sedang", ingredients: [{ name: "udang, bihun", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Siram udang segar dengan kuah kaldu rempah tanpa santan." }], tags: ["soto berkuah", "udang"], categories: ["makanan berkuah"] },
    { id: "menusa_0084", title: "Nasi Tiwul", origin_region: "Jawa", cuisine_subtype: "Nusantara", servings: 5, prep_time: 15, cook_time: 30, total_time: 45, difficulty: "mudah", ingredients: [{ name: "tepung gaplek singkong", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Kukus tepung tiwul dan sajikan bersama parutan kelapa / lauk pauk." }], tags: ["nasi tradisional", "singkong"], categories: ["masakan utama"] },
    { id: "menusa_0085", title: "Doclang", origin_region: "Jawa Barat", cuisine_subtype: "Nusantara", servings: 3, prep_time: 15, cook_time: 15, total_time: 30, difficulty: "mudah", ingredients: [{ name: "ketupat, tahu, kentang", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Beri irisan potongan ketupat, tahu dan telor, lalu siram bumbu kacang kental." }], tags: ["bumbu kacang", "jajanan"], categories: ["masakan utama"] },
    { id: "menusa_0086", title: "Burgo", origin_region: "Sumatera Selatan", cuisine_subtype: "Nusantara", servings: 4, prep_time: 30, cook_time: 20, total_time: 50, difficulty: "sedang", ingredients: [{ name: "tepung beras dadar gulung", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Siram potongan dadar gulung tepung beras dengan kuah santan dan kaldu ikan." }], tags: ["dadar tepung", "santan gurih"], categories: ["makanan utama"] },
    { id: "menusa_0087", title: "Pacri Nanas", origin_region: "Sumatera, Kalimantan", cuisine_subtype: "Nusantara", servings: 3, prep_time: 10, cook_time: 20, total_time: 30, difficulty: "mudah", ingredients: [{ name: "buah nanas matang", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Masak nanas dengan bumbu kayu manis, cengkeh dan cuka." }], tags: ["buah", "asam manis pendamping"], categories: ["sayur pendamping"] },
    { id: "menusa_0088", title: "Semur Jengkol", origin_region: "DKI Jakarta", cuisine_subtype: "Nusantara", servings: 4, prep_time: 45, cook_time: 60, total_time: 105, difficulty: "sedang", ingredients: [{ name: "jengkol tua yang diempukkan", quantity: 400, unit: "g" }], steps: [{ number: 1, text: "Rebus empuk dengan abu, geprek pipih, lalu masak dalam semur kecap pekat." }], tags: ["jengkol", "kecap manis"], categories: ["lauk"] },
    { id: "menusa_0089", title: "Pindang Tulang", origin_region: "Sumatera Selatan", cuisine_subtype: "Nusantara", servings: 5, prep_time: 20, cook_time: 90, total_time: 110, difficulty: "sedang", ingredients: [{ name: "tulang rusuk sapi", quantity: 700, unit: "g" }], steps: [{ number: 1, text: "Masak iga tulang dengan nanas segar dan tomat ceri serta bumbu pedas asam manis." }], tags: ["iga tulang", "segar nanas"], categories: ["makanan berkuah"] },
    { id: "menusa_0090", title: "Ayam Pop", origin_region: "Sumatera Barat", cuisine_subtype: "Nusantara", servings: 4, prep_time: 15, cook_time: 30, total_time: 45, difficulty: "sedang", ingredients: [{ name: "Ayam kampung tanpa kulit", quantity: 500, unit: "g" }], steps: [{ number: 1, text: "Ungkep dengan air kelapa pucat, lalu goreng sekilas saja tidak garing." }], tags: ["ayam pucat", "minang kelapa"], categories: ["lauk"] }
];

const allData = [...existingData, ...newRecipes];
writeFileSync('data.json', JSON.stringify(allData, null, 2));
console.log('Added 20 new recipes to data.json, total is now 90');
